name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build assets
        run: |
          npm ci
          npm run build
      - name: Upload via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.HOSTINGER_SFTP_SERVER }}
          port: ${{ secrets.HOSTINGER_SFTP_PORT }}
          username: ${{ secrets.HOSTINGER_SFTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_SFTP_PASSWORD }}
          protocol: sftp
          local-dir: ./
          server-dir: ${{ secrets.HOSTINGER_PATH }}
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            vendor/**
            storage/framework/cache/**
            storage/logs/**
            tests/**
      - name: SSH post-deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          port: ${{ secrets.HOSTINGER_SSH_PORT }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
          script: |
            cd ${{ secrets.HOSTINGER_PATH }}
            if [ ! -f composer.phar ]; then curl -sS https://getcomposer.org/installer | php; fi
            php composer.phar install --no-dev --prefer-dist --no-progress --no-interaction
            php artisan config:cache
            php artisan migrate --force
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
            php artisan storage:link || true

