name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build assets
        run: |
          npm ci
          npm run build
      - name: Upload via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.HOSTINGER_SFTP_SERVER }}
          username: ${{ secrets.HOSTINGER_SFTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_SFTP_PASSWORD }}
          protocol: sftp
          local-dir: ./
          server-dir: ${{ secrets.HOSTINGER_PATH }}
          exclude: |
            **/.git*
            **/.github/**
            node_modules/**
            vendor/**
            storage/framework/cache/**
            storage/logs/**
            tests/**
      - name: SSH post-deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOSTINGER_SSH_HOST }}
          username: ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            cd ${{ secrets.HOSTINGER_PATH }}
            php -d detect_unicode=0 composer.phar install --no-dev --prefer-dist --no-progress --no-interaction
            php artisan migrate --force
            php artisan optimize
            php artisan storage:link || true

